### ISSUE TITLE
Erro on Migration 

### ISSUE THREAD

**Issue by ghost** [codeschool/RFZ2-ZombieTweets#1]
Hi,

First thanks for the course was great.

When I take a look at the code to run the migrations had the following error

rake aborted!
Multiple migrations have the version number 20111004043056

I think that migration can be deleted 20111004043056_add_privacy_to_tweets.rb

**Comment by renz45** [comment]
Sorry about that ghost, I just merged a pull request that should fix the issue. You were absolutely correct, there was a duplicate migration in there for some reason.
